// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/todo.proto

package todo_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName             string   `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2a0928dca4b1b7, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Todo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type GetTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoRequest) Reset()         { *m = GetTodoRequest{} }
func (m *GetTodoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodoRequest) ProtoMessage()    {}
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2a0928dca4b1b7, []int{1}
}

func (m *GetTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoRequest.Unmarshal(m, b)
}
func (m *GetTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoRequest.Marshal(b, m, deterministic)
}
func (m *GetTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoRequest.Merge(m, src)
}
func (m *GetTodoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodoRequest.Size(m)
}
func (m *GetTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoRequest proto.InternalMessageInfo

func (m *GetTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodoResponse struct {
	Response             *Todo    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoResponse) Reset()         { *m = GetTodoResponse{} }
func (m *GetTodoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodoResponse) ProtoMessage()    {}
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2a0928dca4b1b7, []int{2}
}

func (m *GetTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoResponse.Unmarshal(m, b)
}
func (m *GetTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoResponse.Marshal(b, m, deterministic)
}
func (m *GetTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoResponse.Merge(m, src)
}
func (m *GetTodoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodoResponse.Size(m)
}
func (m *GetTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoResponse proto.InternalMessageInfo

func (m *GetTodoResponse) GetResponse() *Todo {
	if m != nil {
		return m.Response
	}
	return nil
}

type CreateTodoRequest struct {
	TaskName             string   `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2a0928dca4b1b7, []int{3}
}

func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (m *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(m, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

type CreateTodoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoResponse) Reset()         { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()    {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2a0928dca4b1b7, []int{4}
}

func (m *CreateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoResponse.Unmarshal(m, b)
}
func (m *CreateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoResponse.Marshal(b, m, deterministic)
}
func (m *CreateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoResponse.Merge(m, src)
}
func (m *CreateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTodoResponse.Size(m)
}
func (m *CreateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoResponse proto.InternalMessageInfo

func (m *CreateTodoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateTodoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Todo)(nil), "todo.api.Todo")
	proto.RegisterType((*GetTodoRequest)(nil), "todo.api.GetTodoRequest")
	proto.RegisterType((*GetTodoResponse)(nil), "todo.api.GetTodoResponse")
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.api.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "todo.api.CreateTodoResponse")
}

func init() { proto.RegisterFile("api/todo.proto", fileDescriptor_ca2a0928dca4b1b7) }

var fileDescriptor_ca2a0928dca4b1b7 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xb5, 0x75, 0x71, 0xeb, 0x08, 0x15, 0xe7, 0x14, 0xab, 0x87, 0x92, 0xd3, 0xe2, 0xa1, 0x0b,
	0xf5, 0xac, 0x08, 0x82, 0x22, 0x82, 0x87, 0x22, 0x78, 0x8e, 0x64, 0x90, 0x22, 0xbb, 0x13, 0x9b,
	0xf8, 0xff, 0x62, 0x48, 0x9a, 0x76, 0x77, 0x6f, 0x6f, 0x32, 0xf3, 0xde, 0xbc, 0x37, 0x81, 0x52,
	0x99, 0x7e, 0xed, 0x58, 0x73, 0x63, 0x06, 0x76, 0x8c, 0x85, 0xc7, 0xca, 0xf4, 0xf2, 0x09, 0x16,
	0xef, 0xac, 0x19, 0x4b, 0xc8, 0x7b, 0x2d, 0xb2, 0x3a, 0x5b, 0x9d, 0x76, 0x79, 0xaf, 0xb1, 0x82,
	0xc2, 0x29, 0xfb, 0xfd, 0xa6, 0x36, 0x24, 0x72, 0xff, 0x3a, 0xd6, 0x88, 0xb0, 0xd0, 0xbc, 0x25,
	0x71, 0x5c, 0x67, 0xab, 0xa2, 0xf3, 0x58, 0xd6, 0x50, 0x3e, 0x93, 0xfb, 0x97, 0xea, 0xe8, 0xe7,
	0x97, 0xac, 0xdb, 0x55, 0x94, 0x77, 0x70, 0x3e, 0x4e, 0x58, 0xc3, 0x5b, 0x4b, 0x78, 0x03, 0xc5,
	0x10, 0xb0, 0x1f, 0x3c, 0x6b, 0xcb, 0x26, 0x3a, 0x6b, 0xfc, 0xe4, 0xd8, 0x97, 0x6b, 0xb8, 0x78,
	0x1c, 0x48, 0x39, 0x9a, 0xee, 0x98, 0xba, 0xcc, 0xe6, 0x2e, 0xe5, 0x3d, 0xe0, 0x94, 0x10, 0x56,
	0xee, 0xe6, 0x14, 0xb0, 0xdc, 0x90, 0xb5, 0xea, 0x2b, 0xc6, 0x8c, 0x65, 0xfb, 0x01, 0x90, 0xf8,
	0xf8, 0x32, 0xab, 0xae, 0x92, 0xcd, 0x3d, 0x53, 0xd5, 0xf5, 0xe1, 0x66, 0xc8, 0x71, 0xd4, 0xbe,
	0xc2, 0x32, 0x1c, 0x02, 0x1f, 0x12, 0x14, 0x89, 0x35, 0x3f, 0x64, 0x75, 0x79, 0xa0, 0x13, 0xc5,
	0x3e, 0x4f, 0xfc, 0x87, 0xde, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xb7, 0x28, 0x55, 0xe2,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreateTodoClient is the client API for CreateTodo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateTodoClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
}

type createTodoClient struct {
	cc *grpc.ClientConn
}

func NewCreateTodoClient(cc *grpc.ClientConn) CreateTodoClient {
	return &createTodoClient{cc}
}

func (c *createTodoClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := c.cc.Invoke(ctx, "/todo.api.CreateTodo/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateTodoServer is the server API for CreateTodo service.
type CreateTodoServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
}

// UnimplementedCreateTodoServer can be embedded to have forward compatible implementations.
type UnimplementedCreateTodoServer struct {
}

func (*UnimplementedCreateTodoServer) CreateTodo(ctx context.Context, req *CreateTodoRequest) (*CreateTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}

func RegisterCreateTodoServer(s *grpc.Server, srv CreateTodoServer) {
	s.RegisterService(&_CreateTodo_serviceDesc, srv)
}

func _CreateTodo_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateTodoServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.api.CreateTodo/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateTodoServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreateTodo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.api.CreateTodo",
	HandlerType: (*CreateTodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _CreateTodo_CreateTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/todo.proto",
}

// GetTodoClient is the client API for GetTodo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetTodoClient interface {
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error)
}

type getTodoClient struct {
	cc *grpc.ClientConn
}

func NewGetTodoClient(cc *grpc.ClientConn) GetTodoClient {
	return &getTodoClient{cc}
}

func (c *getTodoClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error) {
	out := new(GetTodoResponse)
	err := c.cc.Invoke(ctx, "/todo.api.GetTodo/GetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTodoServer is the server API for GetTodo service.
type GetTodoServer interface {
	GetTodo(context.Context, *GetTodoRequest) (*GetTodoResponse, error)
}

// UnimplementedGetTodoServer can be embedded to have forward compatible implementations.
type UnimplementedGetTodoServer struct {
}

func (*UnimplementedGetTodoServer) GetTodo(ctx context.Context, req *GetTodoRequest) (*GetTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodo not implemented")
}

func RegisterGetTodoServer(s *grpc.Server, srv GetTodoServer) {
	s.RegisterService(&_GetTodo_serviceDesc, srv)
}

func _GetTodo_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetTodoServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.api.GetTodo/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetTodoServer).GetTodo(ctx, req.(*GetTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetTodo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.api.GetTodo",
	HandlerType: (*GetTodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodo",
			Handler:    _GetTodo_GetTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/todo.proto",
}
